name: check-if-date-is-holiday test

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  check-if-date-is-holiday:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check date
        id: check-date
        run: |
          echo "DATE=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"

      - name: Check date and exit if the date is outside the range
        if: ${{ github.event_name != 'workflow_dispatch' && '2025-04-30' <= steps.check-date.outputs.DATE && steps.check-date.outputs.DATE <= '2025-05-05' }}
        run: exit 1
